// <auto-generated />
using Intranet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intranet.Migrations.BdoPE
{
    [DbContext(typeof(BdoPEContext))]
    [Migration("20191007082600_InitialBdoPECreate")]
    partial class InitialBdoPECreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intranet.Models.BdoPE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccMatNextLine")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("AccMatNextLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("AmountDocCur")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AmountDocCur2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AssignNum")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BaseDateDueCal")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CurrentKey")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DocDateInDoc")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DocHeadT")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FiscalPeriod")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ItemText")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ItemText2")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MarketerZ2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PosDateInDoc")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PosKeyInNextLine")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PosKeyInNextLine2")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RefDocNum")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserDate")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserIP")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValDate")
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("isDownloaded");

                    b.HasKey("Id");

                    b.ToTable("bdoPEs");
                });
#pragma warning restore 612, 618
        }
    }
}
