// <auto-generated />
using Intranet.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intranet.DataAccess.Data.Migrations.SOA
{
    [DbContext(typeof(SOADbContext))]
    partial class SOADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intranet.Models.SOA.BKPF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADISC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AEDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARCID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUSBK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWKEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWSYS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASW2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASW3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BELNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BKTXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLIND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRNCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSTAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVORG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CASH_ALLOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUTM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTXKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DBBLG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOCCAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOKID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DUEFL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXCLUDE_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FM_UMART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FOLLOW_ON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRATH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLVOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRPID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HWAE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HWAE3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HWAER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBLAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTDATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTFORM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INWARDDT_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INWARDNO_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KNUMV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUR2X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUR3X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURSF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURSX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUTY2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUTY3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KZKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KZWRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDGRP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOTKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUMPG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OFFSET_REFER_DAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OFFSET_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINETNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OININD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PENRC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPNAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPTCOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPTME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPMANO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOAK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSODT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOFN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOSG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOTM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOZL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYBASDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYBASNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYBASTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYIBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RECHN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REINDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESUBMISSION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLDNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAMPLED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPF15_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSBLK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STBLG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STGRD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STJAH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STODT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBSET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMRD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMRD3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPDDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USNAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATDATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAERS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WWERT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBLNR_ALT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMCA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMWST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNETB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF1_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF2_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREORG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREVERSAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRUEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSNET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSPLIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSTOV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XUSVR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XWVOF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKPFs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.BSAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ABSBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFAE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFBJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFBU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANLN1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANLN2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APLZL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUFNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUFPL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUGBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUGDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUGGJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDIF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDIF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDIFF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BELNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSCHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSTAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUDGET_PD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUPLA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUZEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUZID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCBTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CESSION_KZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DABRZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBE3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGBLD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGLLD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGRUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPFB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETEN2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILKD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIPOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FISTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FKBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FKONT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GMVKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRANT_NBR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HBKID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKONT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKTID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMKEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INFAE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTRENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KBLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KBLPOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KIDNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KKBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOSTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUNNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LANDL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOTKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LZBKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MABER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNDID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSCHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSK1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSK2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSK3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWST2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWST3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OIEXGNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OIEXGTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINETCYC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYS_PROV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYS_TRAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSN2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDIF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDIF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDIFF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPRCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRCTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPMANO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSWBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSWSL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYAMT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYCUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QSSKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFZEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSTGR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAKNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAMNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGTXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHKZG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKFBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKNT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKNT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKNTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STCEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UEBGDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMSKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMSKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UZAWE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBEL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBELN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBEWA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBUND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPOS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAERS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WMWST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WSKTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WVERW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XANET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XARCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCPDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEGDR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XINVE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNEGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNETB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNOZA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPYPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRAGL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSTOV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XZAHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD1P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD1T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD2P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD2T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD3T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZFBDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZINKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZLSCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZLSPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZTERM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZUMSK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZUONR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BSADs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.BSEG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BELNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUZEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKONT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGTXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHKZG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBTR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BSEGs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.BSID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ABSBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFAE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFBJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANFBU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANLN1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANLN2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APLZL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUFNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUFPL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUGBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUGDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUGGJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDIF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDIF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDIFF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BELNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSCHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSTAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUDGET_PD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUPLA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUZEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUZID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCBTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CESSION_KZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DABRZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMB33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBE3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMBTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTWS4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGBLD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGLLD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGRUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPFB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETEN2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILKD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIPOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FISTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FKBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FKONT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GMVKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRANT_NBR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HBKID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKONT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HKTID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMKEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INFAE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTRENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KBLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KBLPOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KIDNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KKBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOSTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUNNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LANDL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOTKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LZBKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MABER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNDID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSCHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSK1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSK2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSK3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWST2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWST3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OIEXGNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OIEXGTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINETCYC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYS_PROV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYS_TRAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSN2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDIF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDIF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDIFF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPRCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRCTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROJN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPMANO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSWBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSWSL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYAMT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYCUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QSSKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBZZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFZEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSTGR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAKNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAMNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGTXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHKZG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKFBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKNT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKNT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKNTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STCEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UEBGDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMSKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMSKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UZAWE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBEL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBELN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBEWA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBUND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPOS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAERS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WMWST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WRBTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WSKTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WVERW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XANET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XARCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCPDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEGDR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XINVE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNEGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNETB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNOZA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPYPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRAGL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSTOV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XZAHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD1P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD1T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD2P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD2T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBD3T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZBFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZFBDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZINKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZLSCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZLSPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZTERM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZUMSK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZUONR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BSIDs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.KNA1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KUNNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORT01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSTLZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STRAS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KNA1s");
                });

            modelBuilder.Entity("Intranet.Models.SOA.KNB1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BUKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUNNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KVERM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KNB1s");
                });

            modelBuilder.Entity("Intranet.Models.SOA.KNKK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KKBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLIMK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUNNR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KNKKs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.KNVK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KUNNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KNVKs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.R_BKPF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADISC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AEDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARCID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUSBK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWKEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWSYS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AWTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASW2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASW3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BELNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BKTXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLIND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRNCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSTAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVORG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CASH_ALLOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCINS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUTM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTXKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DBBLG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOCCAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOKID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DUEFL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXCLUDE_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FM_UMART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FOLLOW_ON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRATH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLVOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRPID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HWAE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HWAE3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HWAER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBLAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTDATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTFORM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INWARDDT_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INWARDNO_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KNUMV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUR2X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUR3X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURSF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KURSX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUTY2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KUTY3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KZKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KZWRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDGRP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOTKZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUMPG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OFFSET_REFER_DAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OFFSET_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINETNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OININD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINJAHR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PENRC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPNAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPTCOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPTME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPMANO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOAK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOBT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSODT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOFN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOSG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOTM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSOZL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYBASDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYBASNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYBASTYP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYIBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RECHN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REINDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESUBMISSION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RLDNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAMPLED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPF15_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSBLK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STBLG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STGRD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STJAH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STODT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBSET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXKRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMRD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UMRD3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPDDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USNAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATDATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAERS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WWERT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBLNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBLNR_ALT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMCA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMWST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNETB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF1_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREF2_HD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREORG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XREVERSAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRUEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSNET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSPLIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSTOV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XUSVR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XWVOF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("R_BKPFs");
                });

            modelBuilder.Entity("Intranet.Models.SOA.T001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADRNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BURKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUTXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STCEG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T001");
                });

            modelBuilder.Entity("Intranet.Models.SOA.T014", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ALLCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTLPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KKBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KKBTX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KLIMK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERIV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SBGRP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STAFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAERS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T014s");
                });

            modelBuilder.Entity("Intranet.Models.SOA.T052", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ZTAG1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZTAG2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZTAG3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZTERM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T052s");
                });
#pragma warning restore 612, 618
        }
    }
}
